name: web-debug

on:
  push:
    branches: [ "001-init-cmake-structure" ]
  pull_request:

jobs:
  web-debug-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preset: [web-debug]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.57
      - name: Cache build directory
        uses: actions/cache@v4
        with:
          path: build/${{ matrix.preset }}
          key: ${{ runner.os }}-${{ matrix.preset }}-${{ github.sha }}
      - name: Configure
        run: cmake --preset ${{ matrix.preset }}
      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}
      - name: Test
        run: ctest --preset ${{ matrix.preset }}
      - name: Generate size reports (parallel)
        run: |
          set -euo pipefail
          folders=(sandbox/wasm/debug sandbox/wasm/release)
          declare -a pids=()
          for folder in "${folders[@]}"; do
            echo "Running size report for ${folder}"
            python3 reports/size/update.py --folder "${folder}" &
            pids+=($!)
          done
          status=0
          for pid in "${pids[@]}"; do
            if ! wait "${pid}"; then
              status=1
            fi
          done
          exit "${status}"
      - name: Upload size and microbench artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset }}-reports
          path: |
            build/${{ matrix.preset }}/tests/size
            build/${{ matrix.preset }}/tests/microbench
