name: win-debug

on:
  push:
    branches: [ "001-init-cmake-structure" ]
  pull_request:

jobs:
  win-debug-build:
    runs-on: windows-latest
    strategy:
      matrix:
        preset: [win-debug]
    steps:
      - uses: actions/checkout@v4
      - name: Cache build directory
        uses: actions/cache@v4
        with:
          path: build\${{ matrix.preset }}
          key: ${{ runner.os }}-${{ matrix.preset }}-${{ github.sha }}
      - name: Configure
        shell: pwsh
        run: cmake --preset ${{ matrix.preset }}
      - name: Build
        shell: pwsh
        run: cmake --build --preset ${{ matrix.preset }}
      - name: Test
        shell: pwsh
        run: ctest --preset ${{ matrix.preset }}
      - name: Generate size reports (parallel)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $repoRoot = (Get-Location).Path
          $folders = @("sandbox/wasm/debug", "sandbox/wasm/release")
          Import-Module ThreadJob
          $jobs = foreach ($folder in $folders) {
            Start-ThreadJob -ScriptBlock {
              param($targetFolder, $root)
              Set-Location $root
              Write-Output "Running size report for $targetFolder"
              python reports/size/update.py --folder $targetFolder
              if ($LASTEXITCODE -ne 0) {
                throw "Size report failed for $targetFolder with exit code $LASTEXITCODE"
              }
            } -ArgumentList $folder, $repoRoot
          }
          $failed = $false
          foreach ($job in $jobs) {
            try {
              Wait-Job $job | Out-Null
              Receive-Job $job
            } catch {
              $failed = $true
              Write-Error $_
            } finally {
              Remove-Job $job | Out-Null
            }
            if ($job.State -ne 'Completed') {
              $failed = $true
            }
          }
          if ($failed) {
            throw "One or more size report jobs failed."
          }
      - name: Upload size and microbench artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset }}-reports
          path: |
            build/${{ matrix.preset }}/tests/size
            build/${{ matrix.preset }}/tests/microbench
